### ISSUE TITLE
Posted url not on GitHub (only local)

### ISSUE THREAD

**Issue by sr320** [MeganEDuffy/FISH-546#4]
Just to let you know - only you can see a url that includes `localhost`

ie
https://github.com/sr320/course-fish546-2016/issues/31#issuecomment-253966561

**Comment by MeganEDuffy** [comment]
Got it, thanks! So I'd have to use
https://github.com/MeganEDuffy/FISH-546/blob/master/notebooks/data/01-etnp_mgf.ipynb
I guess, according to this:
https://help.github.com/articles/getting-permanent-links-to-files/.
